version: 2.1
orbs:
  ci-tools: kanopi/ci-tools@1.4.0
  pantheon: pantheon-systems/pantheon@0.2.0
  cypress: cypress-io/cypress@1
  playground: fauxalgore/playground@0.0.2
workflows:
  build_push_test:
    jobs:
      - pantheon/push